global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.ChangeTracking;
global using MyPerformanceTipsToSpeedUpYourWebAPI.Core;
global using MyPerformanceTipsToSpeedUpYourWebAPI.Core.Model;
global using MyPerformanceTipsToSpeedUpYourWebAPI.Core.Repository;
global using MyPerformanceTipsToSpeedUpYourWebAPI.Data;
global using MyPerformanceTipsToSpeedUpYourWebAPI.Repositories;
global using System.Linq.Expressions;
